// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjf1LQLMv0LK62KGTtPZU9IAByDXbGTG4',
    appId: '1:431131903995:web:00f7eb7ed5a66f36d32d5e',
    messagingSenderId: '431131903995',
    projectId: 'proofofskil',
    authDomain: 'proofofskil.firebaseapp.com',
    storageBucket: 'proofofskil.firebasestorage.app',
    measurementId: 'G-5ZB386Z6R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB-7Um6iVyhheJ0pIVDNLVguSaGidotSE',
    appId: '1:431131903995:android:0e6ae0cc80e84536d32d5e',
    messagingSenderId: '431131903995',
    projectId: 'proofofskil',
    storageBucket: 'proofofskil.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdBYDYT_3SkGgdsEV9CYQaaM5VqeV1gsA',
    appId: '1:431131903995:ios:dc73cc0a03b1a8bdd32d5e',
    messagingSenderId: '431131903995',
    projectId: 'proofofskil',
    storageBucket: 'proofofskil.firebasestorage.app',
    androidClientId: '431131903995-2io4u2j7apmdrtr5mmpd23gcch797dn0.apps.googleusercontent.com',
    iosClientId: '431131903995-q4ajfuim2ofq72tfukvjmsol14d9kj7d.apps.googleusercontent.com',
    iosBundleId: 'com.brainforge.brainforge',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdBYDYT_3SkGgdsEV9CYQaaM5VqeV1gsA',
    appId: '1:431131903995:ios:dc73cc0a03b1a8bdd32d5e',
    messagingSenderId: '431131903995',
    projectId: 'proofofskil',
    storageBucket: 'proofofskil.firebasestorage.app',
    androidClientId: '431131903995-2io4u2j7apmdrtr5mmpd23gcch797dn0.apps.googleusercontent.com',
    iosClientId: '431131903995-q4ajfuim2ofq72tfukvjmsol14d9kj7d.apps.googleusercontent.com',
    iosBundleId: 'com.brainforge.brainforge',
  );

}